# See https://github.com/tedivm/GitConsensus for more information about this file.
version: 2
#
# Consensus Rules
#

# Minimum number of voters
quorum: 3

# Required percentage of "yes" votes (ignoring abstentions)
threshold: 0.74

# Number of hours after last action (commit or opening the pull request) before issue can be merged
mergedelay: 4

# Number of votes at which the mergedelay gets ignored, assuming no negative votes.
delayoverride: 4

# Number of hours after last action (commit or opening the pull request) before issue is autoclosed
timeout: 360

# Don't count any vote from a user who votes for multiple options
prevent_doubles: true


#
# Disabled Consensus Rules
#

# Add extra labels for the vote counts and age when merging
extra_labels: false

# Only process votes by contributors
contributors_only: false

# Only process votes by collaborators
collaborators_only: false
