
global.PRIORITIES_DEFAULT = 6;

global.PRIORITIES_CREEP_DEFAULT = 4;
global.PRIORITIES_CREEP_UPGRADER = 6;

global.PRIORITIES_SPAWNS = 3;
global.PRIORITIES_DEFENSE = 3;

global.PRIORITIES_CITY = 7;

global.PRIORITIES_CONSTRUCTION = 8;
global.PRIORITIES_PLAYER = 8;

global.PRIORITIES_CITY_REBOOT = 9;

global.PRIORITIES_RESPAWNER = 12;
